openapi: "3.0.0"
Metric:
  type: object
  properties:
    type:
      $ref: "./MetricType.yaml#/MetricType"
    selector:
      type: string
      description: The selector
    eventToken:
      description: The event token that should be sent with the notifications in case the click occurred.
      type: string
